spring.application.name=demo
spring.application.name=course-management

# Cấu hình kết nối Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management
spring.datasource.username=postgres
spring.datasource.password=123456

# Cấu hình JPA / Hibernate
# ddl-auto=update: Tự động cập nhật bảng dựa trên Entity class
spring.jpa.hibernate.ddl-auto=update

# Hiển thị các câu lệnh SQL mà Hibernate thực thi xuống console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true